{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inference-gateway
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference-gateway
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: inference-gateway
{{- end }}
