{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway-config
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference-gateway
data:
  config.yaml: |
{{ .Values.gateway.config | indent 4 }}
{{- end }}
