{{- if .Values.qdrant.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- end }}
