{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-headless
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: sentinel
      port: 26379
      targetPort: 26379
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-sentinel
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
